services:
  app:
    build: .
    image: devops-poc-app:local
    container_name: devops-poc-app
    ports:
      - "3000:3000"
    environment:
      APP_ENV: docker-compose
      APP_VERSION: compose-local
    restart: unless-stopped
